version: "3"
services:
  redis:
    image: redis:5.0
    ports:
      - "6379:6379"
    volumes:
      - "/home/docker-redis/data:/data"
      - "/home/docker-redis/conf:/usr/local/etc/redis"
    deploy:
      replicas: 1
    command: redis-server /usr/local/etc/redis/redis.conf
  zookeeper:
    image: zookeeper:3.4
    restart: always
    ports:
      - 2181:2181
