version: '3'

services:
    
    zookeeper:
        image: 'zookeeper'
        container_name: zookeeper
        ports:
          - '2181:2181'
        environment:
          - ALLOW_ANONYMOUS_LOGIN=yes
        networks:
          - zipkin_net  

    es:
        image: elasticsearch:5.6.16
        container_name: es
        environment:
          - discovery.type=single-node
          - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
          - node.name=es
#         volumes:
#           - ./es:/opt/elasticsearch/data
#           - ./elasticsearch.yml:/opt/elasticsearch/elasticsearch.yml
        ulimits:
            memlock:
              soft: -1
              hard: -1
            nofile:
              soft: 65536
              hard: 65536
        ports:
          - 9200:9200
        networks:
          - zipkin_net
          
    kibana:
      image: docker.elastic.co/kibana/kibana:6.3.2
      ports:
         - "5601:5601"
      networks: 
         - zipkin_net
      
    kafka:
        image: 'bitnami/kafka:2'
        container_name: kafka
        ports:
          - '9092:9092'
  
        environment:
          - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
          - ALLOW_PLAINTEXT_LISTENER=
          - ALLOW_PLAINTEXT_LISTENER=yes
        networks:
          - zipkin_net           
        depends_on:
          - zookeeper


networks:
  zipkin_net:

