version: '3'
# https://docs.docker.com/samples/library/rabbitmq/
services: 
    redis:
      image: redis
      command: redis-server --requirepass 111
      ports:
        - "6379:6379"
#     volumes:
#       - ./data:/data

    zookeeper:
      image: zookeeper
      restart: always
      ports:
        - 2181:2181
    mysql:
      image: mysql
      ports:
        - 3306:3306
      command: --default-authentication-plugin=mysql_native_password
      restart: always
      environment:
        MYSQL_ROOT_PASSWORD: 111        
