version: '3'
services: 
    #缓存服务
    redis:
      image: redis
      command: redis-server --requirepass 111
      ports:
        - "6379:6379"
      #volumes:
      #  - ./data:/data
    
    #服务协调
    zookeeper:
      image: zookeeper
      restart: always
      ports:
        - 2181:2181

    #数据库    
    mysql:
      image: mysql
      ports:
        - 3306:3306
      command: --default-authentication-plugin=mysql_native_password
      restart: always
      environment:
        MYSQL_ROOT_PASSWORD: 111
    
    #docker私有仓库 测试地址 http://你的虚拟机ip:5000/v2/
    registry:
        image: registry
        restart: always
        container_name: registry
        ports:
          - 5000:5000
        #volumes:
        #  - /usr/local/docker/registry/data:/var/lib/registry
