version: '3'
services: 
    #部署是要和elassticsearch kafka 在同一个 docker network


    #分布式链路追踪
    zipkin:
      image: openzipkin/zipkin
      container_name: zipkin
      # Environment settings are defined here https://github.com/openzipkin/zipkin/blob/master/zipkin-server/README.md#environment-variables
      environment:
        - STORAGE_TYPE=elasticsearch
        - ES_HOSTS=es
        - COLLECTOR_KAFKA_ENABLED=true
        - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      ports:
        # Port used for the Zipkin UI and HTTP Api
        - 9411:9411


    #微服务依赖图不是实时生成    
    dependencies:
        image: openzipkin/zipkin-dependencies
        container_name: dependencies
        entrypoint: crond -f
        environment:
          - STORAGE_TYPE=elasticsearch
          - ES_HOSTS=es
          # - ZIPKIN_LOG_LEVEL=DEBUG
          # Uncomment to adjust memory used by the dependencies job
          - JAVA_OPTS=-verbose:gc -Xms1G -Xmx1G
