version: '3'

services:
    #docker私有仓库 测试地址 http://你的虚拟机ip:5000/v2/
    #              查看镜像 http://localhost:5000/v2/_catalog
    #              查看镜像标签 http://localhost:5000/v2/[镜像名称]/tags/list
    #              镜像打标签：docker tag zookeeper localhost:5000/zookeeper:latest2
    #              推送镜像： docker push localhost:5000/zookeeper:latest2 
    #              删除镜像： docker exec registry rm -rf /var/lib/registry/docker/registry/v2/repositories/[image] 
    #
    registry:
        image: registry
        restart: always
        container_name: registry
        ports:
          - 5000:5000
        #volumes:
        #  - /usr/local/docker/registry/data:/var/lib/registry

    #缓存服务
    redis:
        image: redis
        container_name: redis
        command: redis-server --requirepass 111
        ports:
          - "6379:6379"
        #volumes:
        #  - ./data:/data
    zookeeper:
        image: 'zookeeper'
        container_name: zookeeper
        ports:
          - '2181:2181'
        environment:
          - ALLOW_ANONYMOUS_LOGIN=yes

    #数据库    
    mysql:
        image: mysql
        container_name: mysql
        ports:
          - 3306:3306
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
          MYSQL_ROOT_PASSWORD: 111
    
    #查看所有索引：http://localhost:9200/_cat/indices?v
    #查看索引下数据：http://localhost:9200/[索引名称]/_search
    es:
        image: elasticsearch:7.3.2
        container_name: es
        environment:
          - discovery.type=single-node
          - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
          - node.name=es
#         volumes:
#           - ./es:/opt/elasticsearch/data
#           - ./elasticsearch.yml:/opt/elasticsearch/elasticsearch.yml
        ulimits:
            memlock:
              soft: -1
              hard: -1
            nofile:
              soft: 65536
              hard: 65536
        ports:
          - 9200:9200

    kafka:
        image: 'bitnami/kafka:2'
        container_name: kafka
        ports:
          - '9092:9092'
  
        environment:
          - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
          - ALLOW_PLAINTEXT_LISTENER=yes
        depends_on:
          - zookeeper

